/* Dữ liệu Bộ sưu tập và tỉ lệ rương Evil Hunter Tycoon. Nguồn: dữ liệu chính thức, cập nhật 21/07/2026. */

export const dogamSets = [
{no: 1, set: 'Bộ Thiên Thần Hộ Mệnh Vàng (Công 4%)', cat: 'Cánh', name: 'Cánh Thiên Thần Hộ Mệnh Vàng', eff: 'HP 5%', src: 'Sân trước Thành ma vương tầng 90', rate: null, key: 'item-001'},
{no: 1, set: 'Bộ Thiên Thần Hộ Mệnh Vàng (Công 5%)', cat: 'Ấn chương', name: 'Ấn Chương Thiên Thần Hộ Mệnh Vàng', eff: 'HP 5%', src: 'Sân trước Thành ma vương tầng 70', rate: null, key: 'item-002'},
{no: 1, set: 'Bộ Thiên Thần Hộ Mệnh Vàng (Công 3%)', cat: 'Ngoại trang', name: 'Giáp Thiên Thần Hộ Mệnh Vàng', eff: 'Công 0.6%', src: 'Sân trước Thành ma vương tầng 80', rate: null, key: 'item-003'},
{no: 2, set: 'Bộ Xuân Đã Về (Công 3%)', cat: 'Cánh', name: 'Ngoại Trang Cánh Bướm', eff: 'Sát thương Quái nhân 5%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.2, key: 'item-004'},
{no: 2, set: 'Bộ Xuân Đã Về (Công 3%)', cat: 'Ngoại trang', name: 'Ngoại trang váy xuân', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-005'},
{no: 2, set: 'Bộ Xuân Đã Về (Công 3%)', cat: 'Ngoại trang', name: 'Ngoại trang hoa', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-006'},
{no: 3, set: 'Nhà Sưu Tập Vũ Khí - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại Trang Vũ Khí Cà Rốt Tươi', eff: 'Thủ 3%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-007'},
{no: 3, set: 'Nhà Sưu Tập Vũ Khí - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang vũ khí cưa', eff: 'Sát thương 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-008'},
{no: 3, set: 'Nhà Sưu Tập Vũ Khí - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang vũ khí Violin', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-009'},
{no: 3, set: 'Nhà Sưu Tập Vũ Khí - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại Trang Kiếm Tổng Lãnh Thiên Thần', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-010'},
{no: 3, set: 'Nhà Sưu Tập Vũ Khí - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang lưỡi lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-011'},
{no: 4, set: 'Bộ Dụng Cụ (Công 1%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang vũ khí kéo', eff: 'Sát thương 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-012'},
{no: 4, set: 'Bộ Dụng Cụ (Công 1%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang vũ khí cưa', eff: 'Sát thương 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-008'},
{no: 4, set: 'Bộ Dụng Cụ (Công 1%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang vũ khí cờ lê', eff: 'Sát thương 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-013'},
{no: 4, set: 'Bộ Dụng Cụ (Công 1%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang vũ khí búa', eff: 'Sát thương 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-014'},
{no: 5, set: 'Bộ Ngoài Vòng Pháp Luật (Công 1%)', cat: 'Ngoại trang', name: 'Sát Thủ', eff: 'Kinh nghiệm 5%', src: '120 đá quý', rate: null, key: 'item-015'},
{no: 5, set: 'Bộ Ngoài Vòng Pháp Luật (Công 1%)', cat: 'Ngoại trang', name: 'Hải Tặc', eff: 'HP 0.8%', src: '150 đá quý', rate: null, key: 'item-016'},
{no: 5, set: 'Bộ Ngoài Vòng Pháp Luật (Công 1%)', cat: 'Ngoại trang', name: 'Ngoại trang vua phía Bắc', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-017'},
{no: 6, set: 'Bộ Sưu Tập Cánh (Công 5%)', cat: 'Cánh', name: 'Ngoại Trang Cánh Bướm', eff: 'Sát thương Quái nhân 5%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.2, key: 'item-004'},
{no: 6, set: 'Bộ Sưu Tập Cánh (Công 5%)', cat: 'Cánh', name: 'Ngoại Trang Cánh Quạ', eff: 'Sát thương 5%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.2, key: 'item-018'},
{no: 6, set: 'Bộ Sưu Tập Cánh (Công 5%)', cat: 'Cánh', name: 'Ngoại Trang Cánh Tiên Nữ', eff: 'Chí mạng 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.2, key: 'item-019'},
{no: 6, set: 'Bộ Sưu Tập Cánh (Công 5%)', cat: 'Cánh', name: 'Cánh Thiên Thần Hộ Mệnh Vàng', eff: 'HP 5%', src: 'Sân trước Thành ma vương tầng 90', rate: null, key: 'item-001'},
{no: 6, set: 'Bộ Sưu Tập Cánh (Công 5%)', cat: 'Cánh', name: 'Cánh Người Chiến Thắng', eff: 'Công 3%', src: '10000 điểm Chiến Thắng', rate: null, key: 'item-020'},
{no: 7, set: 'Bộ Chinh Phục Đột Kích Liên Minh 2 (Công 3%)', cat: 'Vũ khí Xạ thủ', name: 'Cung Kẻ Thống Trị', eff: 'Công 0.6%', src: 'Răng hàm bậc 13', rate: null, key: 'item-021'},
{no: 7, set: 'Bộ Chinh Phục Đột Kích Liên Minh 2 (Công 3%)', cat: 'Vũ khí Berserker', name: 'Kiếm Kẻ Thống Trị', eff: 'Công 0.6%', src: 'Răng hàm bậc 17', rate: null, key: 'item-022'},
{no: 7, set: 'Bộ Chinh Phục Đột Kích Liên Minh 2 (Công 3%)', cat: 'Vũ khí Pháp sư', name: 'Trượng Kẻ Thống Trị', eff: 'Công 0.6%', src: 'Răng hàm bậc 11', rate: null, key: 'item-023'},
{no: 7, set: 'Bộ Chinh Phục Đột Kích Liên Minh 2 (Công 3%)', cat: 'Vũ khí Paladin', name: 'Lưỡi Hái Kẻ Thống Trị', eff: 'Công 0.6%', src: 'Răng hàm bậc 15', rate: null, key: 'item-024'},
{no: 7, set: 'Bộ Chinh Phục Đột Kích Liên Minh 2 (Công 3%)', cat: 'Ngoại trang', name: 'Kẻ Thống Trị', eff: 'HP 1.6%', src: 'Răng hàm bậc 19', rate: null, key: 'item-025'},
{no: 8, set: 'Bộ Đại Cao Thủ (Công 3%)', cat: 'Vũ khí Xạ thủ', name: 'Đại Cao Thủ Cung', eff: 'Boss 1%', src: '4000 điểm danh dự Đại Cao Thủ', rate: null, key: 'item-026'},
{no: 8, set: 'Bộ Đại Cao Thủ (Công 3%)', cat: 'Vũ khí Berserker', name: 'Đại Cao Thủ Kiếm', eff: 'Boss 1%', src: '3000 điểm danh dự Đại Cao Thủ', rate: null, key: 'item-027'},
{no: 8, set: 'Bộ Đại Cao Thủ (Công 3%)', cat: 'Vũ khí Pháp sư', name: 'Đại Cao Thủ Trượng', eff: 'Boss 1%', src: '4500 điểm danh dự Đại Cao Thủ', rate: null, key: 'item-028'},
{no: 8, set: 'Bộ Đại Cao Thủ (Công 3%)', cat: 'Vũ khí Paladin', name: 'Đại Cao Thủ Búa', eff: 'Boss 1%', src: '3500 điểm danh dự Đại Cao Thủ', rate: null, key: 'item-029'},
{no: 8, set: 'Bộ Đại Cao Thủ (Công 3%)', cat: 'Ngoại trang', name: 'Đại Cao Thủ', eff: 'Công 0.6%', src: '2000 điểm danh dự Đại Cao Thủ', rate: null, key: 'item-030'},
{no: 9, set: 'Bộ Ẩm Thực (Công 2%)', cat: 'Cánh', name: 'Ngoại trang Túi Đồ hộp', eff: 'Công 1.5%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.5, key: 'item-031'},
{no: 9, set: 'Bộ Ẩm Thực (Công 2%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang Vũ khí Pretzel', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-032'},
{no: 9, set: 'Bộ Ẩm Thực (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang Vũ khí Xúc xích', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-033'},
{no: 9, set: 'Bộ Ẩm Thực (Công 2%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang Vũ khí Bông lan cuộn', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-034'},
{no: 9, set: 'Bộ Ẩm Thực (Công 2%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang Vũ khí Sườn cừu', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-035'},
{no: 10, set: 'Bộ Thiên Thần Sa Ngã (Công 5%)', cat: 'Ngoại trang', name: 'Giáp Trụ Đại Thiên Thần', eff: 'Công 0.6%', src: 'Khó,Siêu Khó, Cực Khó Boss Thế Giới', rate: null, key: 'item-036'},
{no: 10, set: 'Bộ Thiên Thần Sa Ngã (Công 5%)', cat: 'Ngoại trang', name: 'Giáp Trụ Uriel', eff: 'Công 0.6%', src: 'Siêu Khó, Cực Khó Boss Thế Giới', rate: null, key: 'item-037'},
{no: 10, set: 'Bộ Thiên Thần Sa Ngã (Công 5%)', cat: 'Ngoại trang', name: 'Giáp Trụ Raphael', eff: 'Công 0.6%', src: 'Cực Khó Boss Thế Giới', rate: null, key: 'item-038'},
{no: 11, set: 'Bộ Vũ Khí Đáng Yêu (Công 3%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang Cung đáng yêu', eff: 'Sát thương 3%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-039'},
{no: 11, set: 'Bộ Vũ Khí Đáng Yêu (Công 3%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang Kiếm đáng yêu', eff: 'Sát thương 3%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-040'},
{no: 11, set: 'Bộ Vũ khí đáng yêu (Công 3%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang Đũa phép đáng yêu', eff: 'Sát thương 3%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-041'},
{no: 11, set: 'Bộ Vũ Khí Đáng Yêu (Công 3%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang Búa đáng yêu', eff: 'Sát thương 3%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-042'},
{no: 12, set: 'Bộ Vũ Khí Ăn Vặt', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang Vũ khí tôm', eff: 'HP 2%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-043'},
{no: 12, set: 'Bộ Vũ Khí Ăn Vặt', cat: 'Vũ khí Berserker', name: 'Ngoại trang Vũ khí nĩa', eff: 'HP 2%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-044'},
{no: 12, set: 'Bộ Vũ Khí Ăn Vặt', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang Vũ khí Marshmallow', eff: 'HP 2%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-045'},
{no: 12, set: 'Bộ Vũ Khí Ăn Vặt', cat: 'Vũ khí Paladin', name: 'Ngoại trang Vũ khí bánh cá', eff: 'HP 2%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-046'},
{no: 13, set: 'Bộ Sưu Tập Cánh 2 (Công 5%)', cat: 'Cánh', name: 'Ngoại trang Cánh rồng hỗn độn', eff: 'Boss 5%', src: 'Rương Bí mật Thị trưởng', rate: 0.4, key: 'item-047'},
{no: 13, set: 'Bộ Sưu Tập Cánh 2 (Công 5%)', cat: 'Cánh', name: 'Ngoại trang Cánh sương giá', eff: 'Sát thương 5%', src: 'Rương Bí mật Thị trưởng', rate: 0.4, key: 'item-048'},
{no: 13, set: 'Bộ Sưu Tập Cánh 2 (Công 5%)', cat: 'Cánh', name: 'Ngoại trang cánh giấc mơ', eff: 'Sát thương Quái nhân 5%', src: 'Rương Bí mật Thị trưởng', rate: 0.4, key: 'item-049'},
{no: 13, set: 'Bộ Sưu Tập Cánh 2 (Công 5%)', cat: 'Cánh', name: 'Cánh Thiên Thần Hộ Mệnh Vàng', eff: 'HP 5%', src: 'Sân trước Thành ma vương tầng 90', rate: null, key: 'item-001'},
{no: 13, set: 'Bộ Sưu Tập Cánh 2 (Công 5%)', cat: 'Cánh', name: 'Cánh Người Chiến Thắng', eff: 'Công 3%', src: '10000 điểm Chiến Thắng', rate: null, key: 'item-020'},
{no: 14, set: 'Bộ Diệt Rồng (Công 3%)', cat: 'Cánh', name: 'Ngoại trang Cánh rồng hỗn độn', eff: 'Boss 5%', src: 'Rương Bí mật Thị trưởng', rate: 0.4, key: 'item-047'},
{no: 14, set: 'Bộ Diệt Rồng (Công 3%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang Kiếm Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-050'},
{no: 14, set: 'Bộ Diệt Rồng (Công 3%)', cat: 'Ngoại trang', name: 'Bậc Thầy Đấu Sĩ', eff: 'Công 0.6%', src: 'Cửa hàng PVP', rate: null, key: 'item-051'},
{no: 15, set: 'Nhà Sưu Tập Vũ Khí 2 - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang Vũ khí Xúc xích', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-033'},
{no: 15, set: 'Nhà Sưu Tập Vũ Khí 2 - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang Vũ khí nĩa', eff: 'HP 2%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-044'},
{no: 15, set: 'Nhà Sưu Tập Vũ Khí 2 - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang Kiếm Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-050'},
{no: 15, set: 'Nhà Sưu Tập Vũ Khí 2 - Berserker (Công 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang Kiếm đáng yêu', eff: 'Sát thương 3%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-040'},
{no: 16, set: 'Bộ Bốn Mùa (Thủ 8%)', cat: 'Ngoại trang', name: 'Ngoại trang váy xuân', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-005'},
{no: 16, set: 'Bộ Bốn Mùa (Thủ 8%)', cat: 'Ngoại trang', name: 'Ngoại trang dạo biển', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-052'},
{no: 16, set: 'Bộ Bốn Mùa (Thủ 8%)', cat: 'Ngoại trang', name: 'Ngoại trang áo trench coat', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-053'},
{no: 16, set: 'Bộ Bốn Mùa (Thủ 8%)', cat: 'Ngoại trang', name: 'Ngoại trang lễ phục mùa đông', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-054'},
{no: 17, set: 'Nhà Sưu Tập Vũ Khí - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại Trang Vũ Khí Băng Nhũ', eff: 'Thủ 3%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-055'},
{no: 17, set: 'Nhà Sưu Tập Vũ Khí - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang vũ khí búa', eff: 'Sát thương 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-014'},
{no: 17, set: 'Nhà Sưu Tập Vũ Khí - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang vũ khí guitar điện', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-056'},
{no: 17, set: 'Nhà Sưu Tập Vũ Khí - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại Trang Búa Tổng Lãnh Thiên Thần', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-057'},
{no: 17, set: 'Nhà Sưu Tập Vũ Khí - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang búa lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-058'},
{no: 18, set: 'Bộ Dạ Tiệc (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại trang tiệc đêm', eff: 'Thủ 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-059'},
{no: 18, set: 'Bộ Dạ Tiệc (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Bếp Trưởng', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-060'},
{no: 18, set: 'Bộ Dạ Tiệc (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Bánh Gatô', eff: 'Thủ 1%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-061'},
{no: 19, set: 'Bộ Đồng Phục (Thủ 5%)', cat: 'Ngoại trang', name: 'Đồng Phục Trắng', eff: 'Giảm 10% độ đói', src: '150 đá quý', rate: null, key: 'item-062'},
{no: 19, set: 'Bộ Đồng Phục (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Đồng Phục Đỏ', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-063'},
{no: 20, set: 'Bộ Đồng phục (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Học Sinh Thủy Thủ', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-064'},
{no: 20, set: 'Bộ Đồng phục (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại trang đồng phục hồng', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-065'},
{no: 20, set: 'Bộ Đồng phục (Thủ 5%)', cat: 'Ngoại trang', name: 'Đồng Phục Học Viện', eff: 'Nhận thêm 20% Sách Kỹ Năng', src: '200 đá quý', rate: null, key: 'item-066'},
{no: 21, set: 'Bộ Dạ Tiệc Mùa Đông (Thủ 8%)', cat: 'Ngoại trang', name: 'Ngoại trang Tiệc cuối năm', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-067'},
{no: 21, set: 'Bộ Dạ Tiệc Mùa Đông (Thủ 8%)', cat: 'Ngoại trang', name: 'Ngoại trang Tiên Noel', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-068'},
{no: 21, set: 'Bộ Dạ Tiệc Mùa Đông (Thủ 8%)', cat: 'Ngoại trang', name: 'Ngoại trang trang trọng Holiday', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-069'},
{no: 22, set: 'Bộ Đồng phục 2 (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Đồng phục xưa', eff: 'Công 0.3%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-070'},
{no: 22, set: 'Bộ Đồng phục 2 (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Học Sinh Thủy Thủ', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-064'},
{no: 22, set: 'Bộ Đồng phục 2 (Thủ 5%)', cat: 'Ngoại trang', name: 'Ngoại trang đồng phục hồng', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-065'},
{no: 23, set: 'Nhà Sưu Tập Vũ Khí 2 - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang Vũ khí Sườn cừu', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-035'},
{no: 23, set: 'Nhà Sưu Tập Vũ Khí 2 - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang Vũ khí bánh cá', eff: 'HP 2%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-046'},
{no: 23, set: 'Nhà Sưu Tập Vũ Khí 2 - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang Búa Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-071'},
{no: 23, set: 'Nhà Sưu Tập Vũ Khí 2 - Hiệp sĩ (Thủ 8%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang Búa đáng yêu', eff: 'Sát thương 3%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-042'},
{no: 24, set: 'Bộ Hộ Vệ (HP 8%)', cat: 'Ngoại trang', name: 'Ngoại trang hộ vệ', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.2, key: 'item-072'},
{no: 24, set: 'Bộ Hộ Vệ (HP 8%)', cat: 'Ngoại trang', name: 'Giáp Trụ Uriel', eff: 'Công 0.6%', src: 'Siêu Khó, Cực Khó Boss Thế Giới', rate: null, key: 'item-037'},
{no: 25, set: 'Bộ Thời Joseon (HP 5%)', cat: 'Ngoại trang', name: 'Hanbok', eff: 'Kinh nghiệm 5%', src: '120 đá quý', rate: null, key: 'item-073'},
{no: 25, set: 'Bộ Thời Joseon (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang lễ phục năm mới', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-074'},
{no: 25, set: 'Bộ Thời Joseon (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Triều Đại thời Joseon', eff: 'Kinh nghiệm 5%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-075'},
{no: 26, set: 'Bộ Vui Chơi Dưới Nước (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Đồ Bơi', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-076'},
{no: 26, set: 'Bộ Vui Chơi Dưới Nước (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Phao hồng', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-077'},
{no: 26, set: 'Bộ Vui Chơi Dưới Nước (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang dạo biển', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-052'},
{no: 27, set: 'Bộ Tiệc Trà (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Tiệc Dã Ngoại', eff: 'Thủ 1%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-078'},
{no: 27, set: 'Bộ Tiệc Trà (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang hoa', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-006'},
{no: 27, set: 'Bộ Tiệc Trà (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang bánh quy gừng', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-079'},
{no: 28, set: 'Bộ Đầu Bếp Và Nguyên Liệu (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Bếp Trưởng', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-060'},
{no: 28, set: 'Bộ Đầu Bếp Và Nguyên Liệu (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang cà chua', eff: 'Thủ 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-080'},
{no: 28, set: 'Bộ Đầu Bếp Và Nguyên Liệu (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang dứa', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-081'},
{no: 29, set: 'Bộ Tình Ca Mùa Thu (HP 5%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang vũ khí Violin', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-009'},
{no: 29, set: 'Bộ Tình Ca Mùa Thu (HP 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang vũ khí Micro', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-082'},
{no: 29, set: 'Bộ Tình Ca Mùa Thu (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Người sành điệu mùa thu', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-083'},
{no: 30, set: 'Bộ Xứ Sở Cổ Tích (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Ếch xanh', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-084'},
{no: 30, set: 'Bộ Xứ Sở Cổ Tích (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Hầu gái Mèo', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-085'},
{no: 30, set: 'Bộ Xứ Sở Cổ Tích (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Hoàng tử & Công chúa', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-086'},
{no: 31, set: 'Bộ Giấc Mơ Ngọt Ngào (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Kẹo ngọt', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-087'},
{no: 31, set: 'Bộ Giấc Mơ Ngọt Ngào (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Đồ ngủ', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-088'},
{no: 31, set: 'Bộ Xứ sở giấc mơ ngọt ngào (HP 5%)', cat: 'Ngoại trang', name: 'Trang phục ngủ màu cam', eff: 'HP 0.8%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-089'},
{no: 32, set: 'Bộ Hành Trình Của Ong Mật (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang ong mật', eff: 'Công 0.6%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-090'},
{no: 32, set: 'Bộ Hành Trình Của Ong Mật (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang hoa', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-006'},
{no: 32, set: 'Bộ Hành Trình Của Ong Mật (HP 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Ếch xanh', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-084'},
{no: 33, set: 'Nhà Sưu Tập Vũ Khí 2 - Xạ thủ (HP 5%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang Vũ khí Pretzel', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-032'},
{no: 33, set: 'Nhà Sưu Tập Vũ Khí 2 - Xạ thủ (HP 5%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang Vũ khí tôm', eff: 'HP 2%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-043'},
{no: 33, set: 'Nhà Sưu Tập Vũ Khí 2 - Xạ thủ (HP 5%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang Cung Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-091'},
{no: 33, set: 'Nhà Sưu Tập Vũ Khí 2 - Xạ thủ (HP 5%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang Cung đáng yêu', eff: 'Sát thương 3%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-039'},
{no: 34, set: 'Bộ Phù Thủy Bóng Tối (Chí mạng 3%)', cat: 'Cánh', name: 'Ngoại Trang Cánh Quạ', eff: 'Sát thương 5%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.2, key: 'item-018'},
{no: 34, set: 'Bộ Phù Thủy Bóng Tối (Chí mạng 3%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang trượng lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-092'},
{no: 34, set: 'Bộ Phù Thủy Bóng Tối (Chí mạng 3%)', cat: 'Ngoại trang', name: 'Ngoại Trang Halloween', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-093'},
{no: 35, set: 'Bộ Vũ Khí Sức Mạnh (Chí mạng 2%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang cung lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-094'},
{no: 35, set: 'Bộ Vũ Khí Sức Mạnh (Chí mạng 2%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang lưỡi lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-011'},
{no: 35, set: 'Bộ Vũ Khí Sức Mạnh (Chí mạng 2%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang trượng lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-092'},
{no: 35, set: 'Bộ Vũ Khí Sức Mạnh (Chí mạng 2%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang búa lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-058'},
{no: 36, set: 'Nhà Sưu Tập Vũ Khí - Xạ thủ (Chí mạng 2%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại Trang Vũ Khí Hải Mã', eff: 'Thủ 3%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-095'},
{no: 36, set: 'Nhà Sưu Tập Vũ Khí - Xạ thủ (Chí mạng 2%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang vũ khí kéo', eff: 'Sát thương 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-012'},
{no: 36, set: 'Nhà Sưu Tập Vũ Khí - Xạ thủ (Chí mạng 2%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang vũ khí đàn Harp', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-096'},
{no: 36, set: 'Nhà Sưu Tập Vũ Khí - Xạ thủ (Chí mạng 2%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại Trang Cung Tổng Lãnh Thiên Thần', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-097'},
{no: 36, set: 'Nhà Sưu Tập Vũ Khí - Xạ thủ (Chí mạng 2%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang cung lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-094'},
{no: 37, set: 'Bộ Tuổi Thơ Hộ Vệ (Chí mạng 1%)', cat: 'Ngoại trang', name: 'Trẻ Em', eff: 'Thủ 1%', src: '150 đá quý', rate: null, key: 'item-098'},
{no: 37, set: 'Bộ Tuổi Thơ Hộ Vệ (Chí mạng 1%)', cat: 'Ngoại trang', name: 'Ngoại Trang Santa', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-099'},
{no: 37, set: 'Bộ Tuổi Thơ Hộ Vệ (Chí mạng 1%)', cat: 'Ngoại trang', name: 'Rudolph', eff: 'HP 0.8%', src: '150 đá quý', rate: null, key: 'item-100'},
{no: 37, set: 'Bộ Tuổi Thơ Hộ Vệ (Chí mạng 1%)', cat: 'Ngoại trang', name: 'Ngoại trang cao bồi', eff: 'HP 1.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-101'},
{no: 38, set: 'Bộ Tuổi Thơ Hộ Vệ2 (Chí mạng 2%)', cat: 'Cánh', name: 'Ngoại trang Bóng bay trái tim', eff: 'HP 2.5%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.5, key: 'item-102'},
{no: 38, set: 'Bộ Tuổi Thơ Hộ Vệ2 (Chí mạng 2%)', cat: 'Ngoại trang', name: 'Ngoại trang Kẹo ngọt', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-087'},
{no: 38, set: 'Bộ Tuổi Thơ Hộ Vệ2 (Chí mạng 2%)', cat: 'Ngoại trang', name: 'Ngoại trang Thỏ vũ trụ', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-103'},
{no: 38, set: 'Bộ Tuổi Thơ Hộ Vệ2 (Chí mạng 2%)', cat: 'Ngoại trang', name: 'Ngoại trang Đồ ngủ', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-088'},
{no: 39, set: 'Bộ Tiên Mùa Đông (Sát thương 7%)', cat: 'Cánh', name: 'Ngoại Trang Cánh Tiên Nữ', eff: 'Chí mạng 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.2, key: 'item-019'},
{no: 39, set: 'Bộ Tiên Mùa Đông (Sát thương 7%)', cat: 'Vũ khí Paladin', name: 'Ngoại Trang Vũ Khí Băng Nhũ', eff: 'Thủ 3%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-055'},
{no: 39, set: 'Bộ Tiên Mùa Đông (Sát thương 7%)', cat: 'Ngoại trang', name: 'Ngoại trang lễ phục mùa đông', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-054'},
{no: 40, set: 'Bộ Liên Minh (Sát thương 7%)', cat: 'Cánh', name: 'Cánh Người Chiến Thắng', eff: 'Công 3%', src: '10000 điểm Chiến Thắng', rate: null, key: 'item-020'},
{no: 40, set: 'Bộ Liên Minh (Sát thương 7%)', cat: 'Ấn chương', name: 'Ấn chương Người Chiến Thắng', eff: 'Công 3%', src: '10000 điểm Chiến Thắng', rate: null, key: 'item-104'},
{no: 41, set: 'Nhà Sưu Tập Vũ Khí - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại Trang Vũ Khí Kẹo Mút', eff: 'Thủ 3%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-105'},
{no: 41, set: 'Nhà Sưu Tập Vũ Khí - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang vũ khí cờ lê', eff: 'Sát thương 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-013'},
{no: 41, set: 'Nhà Sưu Tập Vũ Khí - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang vũ khí Micro', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-082'},
{no: 41, set: 'Nhà Sưu Tập Vũ Khí - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại Trang Trượng Tổng Lãnh Thiên Thần', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-106'},
{no: 41, set: 'Nhà Sưu Tập Vũ Khí - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang trượng lực', eff: 'Chí mạng 1%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-092'},
{no: 42, set: 'Bộ Ban Nhạc Evil Hunter (Sát thương 3%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang vũ khí đàn Harp', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-096'},
{no: 42, set: 'Bộ Ban Nhạc Evil Hunter (Sát thương 3%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang vũ khí Violin', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-009'},
{no: 42, set: 'Bộ Ban Nhạc Evil Hunter (Sát thương 3%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang vũ khí Micro', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-082'},
{no: 42, set: 'Bộ Ban Nhạc Evil Hunter (Sát thương 3%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang vũ khí guitar điện', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.4, key: 'item-056'},
{no: 43, set: 'Bộ Đại Cao Thủ 2 (Sát thương 7%)', cat: 'Cánh', name: 'Đại Cao Thủ Cánh', eff: 'Boss 5%', src: '7000 điểm danh dự Đại Cao Thủ', rate: null, key: 'item-107'},
{no: 43, set: 'Bộ Đại Cao Thủ 2 (Sát thương 7%)', cat: 'Ấn chương', name: 'Đại Cao Thủ Ấn chương', eff: 'Công 3%', src: '10000 điểm danh dự Đại Cao Thủ', rate: null, key: 'item-108'},
{no: 44, set: 'Bộ Kinh Dị 2 (Sát thương 5%)', cat: 'Cánh', name: 'Ngoại trang Truyền dịch', eff: 'Thủ 5%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.5, key: 'item-109'},
{no: 44, set: 'Bộ Kinh Dị 2 (Sát thương 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Pháp sư Bí ngô', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-110'},
{no: 44, set: 'Bộ Kinh Dị 2 (Sát thương 5%)', cat: 'Ngoại trang', name: 'Ngoại trang phù thủy đen', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-111'},
{no: 44, set: 'Bộ Kinh Dị 2 (Sát thương 5%)', cat: 'Ngoại trang', name: 'Ngoại trang Cương thi', eff: 'HP 1.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-112'},
{no: 45, set: 'Bộ Chinh Phục Đột Kích Liên Minh 3 (Sát thương 10%)', cat: 'Vũ khí Xạ thủ', name: 'Cung Người Thách Đấu', eff: 'Công 0.6%', src: 'Răng khôn bậc 5', rate: null, key: 'item-113'},
{no: 45, set: 'Bộ Chinh Phục Đột Kích Liên Minh 3 (Sát thương 10%)', cat: 'Vũ khí Berserker', name: 'Kiếm Người Thách Đấu', eff: 'Công 0.6%', src: 'Răng khôn bậc 1', rate: null, key: 'item-114'},
{no: 45, set: 'Bộ Chinh Phục Đột Kích Liên Minh 3 (Sát thương 10%)', cat: 'Vũ khí Pháp sư', name: 'Trượng Người Thách Đấu', eff: 'Công 0.6%', src: 'Răng khôn bậc 7', rate: null, key: 'item-115'},
{no: 45, set: 'Bộ Chinh Phục Đột Kích Liên Minh 3 (Sát thương 10%)', cat: 'Vũ khí Paladin', name: 'Búa Người Thách Đấu', eff: 'Công 0.6%', src: 'Răng khôn bậc 3', rate: null, key: 'item-116'},
{no: 45, set: 'Bộ Chinh Phục Đột Kích Liên Minh 3 (Sát thương 10%)', cat: 'Ngoại trang', name: 'Người Thách Đấu', eff: 'HP 1.6%', src: 'Răng khôn bậc 10', rate: null, key: 'item-117'},
{no: 46, set: 'Bộ Dạ Tiệc Ánh Mộng (Sát thương 7%)', cat: 'Cánh', name: 'Ngoại trang cánh giấc mơ', eff: 'Sát thương Quái nhân 5%', src: 'Rương Bí mật Thị trưởng', rate: 0.4, key: 'item-049'},
{no: 46, set: 'Bộ Dạ Tiệc Ánh Mộng (Sát thương 7%)', cat: 'Ngoại trang', name: 'Ngoại trang Hoàng tử & Công chúa', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.655, key: 'item-086'},
{no: 46, set: 'Bộ Dạ Tiệc Ánh Mộng (Sát thương 7%)', cat: 'Ngoại trang', name: 'Ngoại trang váy xuân', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-005'},
{no: 47, set: 'Nhà Sưu Tập Vũ Khí 2 - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang Vũ khí Bông lan cuộn', eff: 'HP 2%', src: 'Hộp ngoại trang lấp lánh B', rate: 2.4, key: 'item-034'},
{no: 47, set: 'Nhà Sưu Tập Vũ Khí 2 - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang Vũ khí Marshmallow', eff: 'HP 2%', src: 'Rương Bí mật Thị trưởng', rate: 2.0, key: 'item-045'},
{no: 47, set: 'Nhà Sưu Tập Vũ Khí 2 - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang Gậy Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-118'},
{no: 47, set: 'Nhà Sưu Tập Vũ Khí 2 - Pháp sư (Sát thương 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang Đũa phép đáng yêu', eff: 'Sát thương 3%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-041'},
{no: 48, set: 'Bộ Đại Thiên Thần (Boss 5%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại Trang Cung Tổng Lãnh Thiên Thần', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-097'},
{no: 48, set: 'Bộ Đại Thiên Thần (Boss 5%)', cat: 'Vũ khí Berserker', name: 'Ngoại Trang Kiếm Tổng Lãnh Thiên Thần', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-010'},
{no: 48, set: 'Bộ Đại Thiên Thần (Boss 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại Trang Trượng Tổng Lãnh Thiên Thần', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-106'},
{no: 48, set: 'Bộ Đại Thiên Thần (Boss 5%)', cat: 'Vũ khí Paladin', name: 'Ngoại Trang Búa Tổng Lãnh Thiên Thần', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh B', rate: 0.7, key: 'item-057'},
{no: 48, set: 'Bộ Đại Thiên Thần (Boss 5%)', cat: 'Ngoại trang', name: 'Giáp Trụ Đại Thiên Thần', eff: 'Công 0.6%', src: 'Khó,Siêu Khó, Cực Khó Boss Thế Giới', rate: null, key: 'item-036'},
{no: 49, set: 'Bộ Chinh Phục Đột Kích Liên Minh (Boss 5%)', cat: 'Vũ khí Xạ thủ', name: 'Chinh Phục Cung', eff: 'Công 0.6%', src: 'Răng hàm bậc 3', rate: null, key: 'item-119'},
{no: 49, set: 'Bộ Chinh Phục Đột Kích Liên Minh (Boss 5%)', cat: 'Vũ khí Berserker', name: 'Chinh Phục Kiếm', eff: 'Công 0.6%', src: 'Răng hàm bậc 7', rate: null, key: 'item-120'},
{no: 49, set: 'Bộ Chinh Phục Đột Kích Liên Minh (Boss 5%)', cat: 'Vũ khí Pháp sư', name: 'Chinh Phục Trượng', eff: 'Công 0.6%', src: 'Răng hàm bậc 1', rate: null, key: 'item-121'},
{no: 49, set: 'Bộ Chinh Phục Đột Kích Liên Minh (Boss 5%)', cat: 'Vũ khí Paladin', name: 'Chinh Phục Búa', eff: 'Công 0.6%', src: 'Răng hàm bậc 5', rate: null, key: 'item-122'},
{no: 49, set: 'Bộ Chinh Phục Đột Kích Liên Minh (Boss 5%)', cat: 'Ngoại trang', name: 'Chinh Phục', eff: 'HP 1.6%', src: 'Răng hàm bậc 10', rate: null, key: 'item-123'},
{no: 50, set: 'Bộ Đại Ác Ma (Boss 5%)', cat: 'Vũ khí Xạ thủ', name: 'Ngoại trang Cung Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-091'},
{no: 50, set: 'Bộ Đại Ác Ma (Boss 5%)', cat: 'Vũ khí Berserker', name: 'Ngoại trang Kiếm Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-050'},
{no: 50, set: 'Bộ Đại Ác Ma (Boss 5%)', cat: 'Vũ khí Pháp sư', name: 'Ngoại trang Gậy Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-118'},
{no: 50, set: 'Bộ Đại Ác Ma (Boss 5%)', cat: 'Vũ khí Paladin', name: 'Ngoại trang Búa Đại ác ma', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.7, key: 'item-071'},
{no: 51, set: 'Bộ Mùa Đông Kẻ Thống Trị (Boss 5%)', cat: 'Cánh', name: 'Ngoại trang Cánh sương giá', eff: 'Sát thương 5%', src: 'Rương Bí mật Thị trưởng', rate: 0.4, key: 'item-048'},
{no: 51, set: 'Bộ Mùa Đông Kẻ Thống Trị (Boss 5%)', cat: 'Ngoại trang', name: 'Ngoại trang lễ phục mùa đông', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-054'},
{no: 51, set: 'Bộ Mùa Đông Kẻ Thống Trị (Boss 5%)', cat: 'Ngoại trang', name: 'Ngoại trang quý tộc mùa đông', eff: 'HP 1.6%', src: 'Rương Bí mật Thị trưởng', rate: 1.0, key: 'item-124'},
{no: 52, set: 'Bộ Ảo Ảnh Ma Vương (Boss 5%)', cat: 'Cánh', name: 'Cánh Ma Vương Xám Tro', eff: 'HP 5%', src: 'Ảo ảnh Ma vương bậc 1 trở lên', rate: null, key: 'item-125'},
{no: 52, set: 'Bộ Ảo Ảnh Ma Vương (Boss 5%)', cat: 'Cánh', name: 'Cánh Ma Vương Đỏ Thẫm', eff: 'Công 3%', src: 'Ảo ảnh Ma vương bậc 4 trở lên', rate: null, key: 'item-126'},
{no: 52, set: 'Bộ Ảo Ảnh Ma Vương (Boss 5%)', cat: 'Ấn chương', name: 'Ấn Chương Ma Vương Đỏ Thẫm', eff: 'Sát thương 5%', src: 'Ảo ảnh Ma vương bậc 3 trở lên', rate: null, key: 'item-127'},
{no: 53, set: 'Bộ Cuồng Chiến (Sát thương Quái nhân 5%)', cat: 'Ngoại trang', name: 'Đấu Sĩ', eff: 'Công 0.3%', src: 'Cửa hàng PVP', rate: null, key: 'item-128'},
{no: 53, set: 'Bộ Cuồng Chiến (Sát thương Quái nhân 5%)', cat: 'Ngoại trang', name: 'Bậc Thầy Đấu Sĩ', eff: 'Công 0.6%', src: 'Cửa hàng PVP', rate: null, key: 'item-051'},
{no: 53, set: 'Bộ Cuồng Chiến (Sát thương Quái nhân 5%)', cat: 'Ngoại trang', name: 'Ngoại trang bạch kim', eff: 'Công 0.6%', src: 'Hộp ngoại trang lấp lánh A', rate: 0.2, key: 'item-129'},
{no: 54, set: 'Bộ Chinh Phục Sân Trước Thành Ma Vương (Ác Ma5%)', cat: 'Ấn chương', name: 'Ấn Chương Kinh Hoàng', eff: 'Giảm 10% độ đói', src: 'Răng hàm bậc 1,2', rate: null, key: 'item-130'},
{no: 54, set: 'Bộ Chinh Phục Sân Trước Thành Ma Vương (Ác Ma5%)', cat: 'Ấn chương', name: 'Ấn Chương Địa Ngục', eff: 'Giảm 10% thể lực tiêu hao', src: 'Răng hàm bậc 2,3,4', rate: null, key: 'item-131'},
{no: 54, set: 'Bộ Chinh Phục Sân Trước Thành Ma Vương (Ác Ma5%)', cat: 'Ấn chương', name: 'Ấn Chương Bóng Tối', eff: 'Giảm 10% tâm trạng tiêu hao', src: 'Răng hàm bậc 4,5,6', rate: null, key: 'item-132'},
{no: 54, set: 'Bộ Chinh Phục Sân Trước Thành Ma Vương (Ác Ma5%)', cat: 'Ấn chương', name: 'Ấn Chương Dối Trá', eff: 'Sát thương 2.5%', src: 'Răng hàm bậc 6,7,8', rate: null, key: 'item-133'},
{no: 54, set: 'Bộ Chinh Phục Sân Trước Thành Ma Vương (Ác Ma5%)', cat: 'Ấn chương', name: 'Ấn Chương Ma Vương', eff: 'Chí mạng 1%', src: 'Răng hàm bậc 8 trở lên', rate: null, key: 'item-134'},
{no: 55, set: 'Bộ Kinh Dị (Xác sống 5%)', cat: 'Ngoại trang', name: 'Ác Ma', eff: 'Kinh nghiệm 5%', src: '120 đá quý', rate: null, key: 'item-135'},
{no: 55, set: 'Bộ Kinh Dị (Xác sống 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Rùng Rợn', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-136'},
{no: 55, set: 'Bộ Kinh Dị (Xác sống 5%)', cat: 'Ngoại trang', name: 'Ngoại Trang Halloween', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-093'},
{no: 56, set: 'Bộ Thú (Thú 5%)', cat: 'Ngoại trang', name: 'Mèo Đen', eff: 'Kinh nghiệm 5%', src: '120 đá quý', rate: null, key: 'item-137'},
{no: 56, set: 'Bộ Thú (Thú 5%)', cat: 'Ngoại trang', name: 'Ngoại trang thỏ hồng', eff: 'Công 0.3%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-138'},
{no: 56, set: 'Bộ Thú (Thú 5%)', cat: 'Ngoại trang', name: 'Ngoại trang gấu', eff: 'HP 0.8%', src: 'Hộp ngoại trang lấp lánh A', rate: 2.655, key: 'item-139'},
{no: 56, set: 'Bộ Thú (Thú 5%)', cat: 'Ngoại trang', name: 'Rudolph', eff: 'HP 0.8%', src: '150 đá quý', rate: null, key: 'item-100'},
{no: 57, set: 'Bộ Hiệp Sĩ Hoàng Gia (Công 3%)', cat: 'Ngoại trang', name: 'Hiệp Sĩ Hoàng Gia', eff: 'Công 0.6%', src: '12000 điểm Đại Cao Thủ', rate: null, key: 'item-140'},
{no: 57, set: 'Bộ Hiệp Sĩ Hoàng Gia (Công 3%)', cat: 'Vũ khí Berserker', name: 'Hiệp Sĩ Hoàng Gia Kiếm', eff: 'Boss 1%', src: '13000 điểm Đại Cao Thủ', rate: null, key: 'item-141'},
{no: 57, set: 'Bộ Hiệp Sĩ Hoàng Gia (Công 3%)', cat: 'Vũ khí Paladin', name: 'Hiệp Sĩ Hoàng Gia Búa', eff: 'Boss 1%', src: '13500 điểm Đại Cao Thủ', rate: null, key: 'item-142'},
{no: 57, set: 'Bộ Hiệp Sĩ Hoàng Gia (Công 3%)', cat: 'Vũ khí Xạ thủ', name: 'Hiệp Sĩ Hoàng Gia Cung', eff: 'Boss 1%', src: '14000 điểm Đại Cao Thủ', rate: null, key: 'item-143'},
{no: 57, set: 'Bộ Hiệp Sĩ Hoàng Gia (Công 3%)', cat: 'Vũ khí Pháp sư', name: 'Hiệp Sĩ Hoàng Gia Trượng', eff: 'Boss 1%', src: '14500 điểm Đại Cao Thủ', rate: null, key: 'item-144'},
{no: 58, set: 'Bộ Chinh Phục Đột Kích Liên Minh 4 (Công 3%)', cat: 'Vũ khí Berserker', name: 'Solaris Kiếm', eff: 'Sát thương 3%', src: 'Răng khôn bậc 17', rate: null, key: 'item-145'},
{no: 58, set: 'Bộ Chinh Phục Đột Kích Liên Minh 4 (Công 3%)', cat: 'Vũ khí Paladin', name: 'Solaris Búa', eff: 'Sát thương 3%', src: 'Răng khôn bậc 16', rate: null, key: 'item-146'},
{no: 58, set: 'Bộ Chinh Phục Đột Kích Liên Minh 4 (Công 3%)', cat: 'Vũ khí Xạ thủ', name: 'Solaris Cung', eff: 'Sát thương 3%', src: 'Răng khôn bậc 14', rate: null, key: 'item-147'},
{no: 58, set: 'Bộ Chinh Phục Đột Kích Liên Minh 4 (Công 3%)', cat: 'Vũ khí Pháp sư', name: 'Solaris Trượng', eff: 'Sát thương 3%', src: 'Răng khôn bậc 13', rate: null, key: 'item-148'},
{no: 58, set: 'Bộ Chinh Phục Đột Kích Liên Minh 4 (Công 3%)', cat: 'Vũ khí Hiệp sĩ Bóng đêm', name: 'Thương Solaris', eff: 'Sát thương 3%', src: 'Răng khôn bậc 11', rate: null, key: 'item-149'},
{no: 59, set: 'Bộ Hiệp Sĩ Hoàng Gia 2 (Sát thương 7%)', cat: 'Cánh', name: 'Hiệp Sĩ Hoàng Gia Cánh', eff: 'Boss 3%', src: '17000 điểm Đại Cao Thủ', rate: null, key: 'item-150'},
{no: 59, set: 'Bộ Hiệp Sĩ Hoàng Gia 2 (Sát thương 7%)', cat: 'Ấn chương', name: 'Hiệp Sĩ Hoàng Gia Ấn chương', eff: 'Công 3%', src: '20000 điểm Đại Cao Thủ', rate: null, key: 'item-151'},
{no: 60, set: 'Bộ Thế Giới - Kẻ Tàn Sát Boss (Boss 10%)', cat: 'Ngoại trang', name: 'Hydra Độc', eff: 'Boss 2%', src: '', rate: null, key: 'item-152'},
{no: 60, set: 'Bộ Thế Giới - Kẻ Tàn Sát Boss (Boss 10%)', cat: 'Ngoại trang', name: 'Chúa Tể Lich', eff: 'Boss 2%', src: '', rate: null, key: 'item-153'},
{no: 60, set: 'Bộ Thế Giới - Kẻ Tàn Sát Boss (Boss 10%)', cat: 'Ngoại trang', name: 'Vua Yeti', eff: 'Boss 2%', src: '', rate: null, key: 'item-154'},
{no: 60, set: 'Bộ Thế Giới - Kẻ Tàn Sát Boss (Boss 10%)', cat: 'Ngoại trang', name: 'Rồng Dung Nham', eff: 'Boss 2%', src: '', rate: null, key: 'item-155'},
{no: 61, set: 'Bộ Thiên Giới (Công 3%)', cat: 'Vũ khí Berserker', name: 'Thiên Giới Kiếm', eff: 'Công 0.6%', src: 'Sân trước Thành ma vương tầng 220', rate: null, key: 'item-156'},
{no: 61, set: 'Bộ Thiên Giới (Công 3%)', cat: 'Vũ khí Paladin', name: 'Thiên Giới Búa', eff: 'Công 0.6%', src: 'Sân trước Thành ma vương tầng 230', rate: null, key: 'item-157'},
{no: 61, set: 'Bộ Thiên Giới (Công 3%)', cat: 'Vũ khí Xạ thủ', name: 'Thiên Giới Cung', eff: 'Công 0.6%', src: 'Sân trước Thành ma vương tầng 240', rate: null, key: 'item-158'},
{no: 61, set: 'Bộ Thiên Giới (Công 3%)', cat: 'Vũ khí Pháp sư', name: 'Thiên Giới Trượng', eff: 'Công 0.6%', src: 'Sân trước Thành ma vương tầng 250', rate: null, key: 'item-159'},
{no: 61, set: 'Bộ Thiên Giới (Công 3%)', cat: 'Vũ khí Hiệp sĩ Bóng đêm', name: 'Thương Thiên Giới', eff: 'Công 0.6%', src: 'Sân trước Thành ma vương tầng 260', rate: null, key: 'item-160'},
];

export const boxAItems = [
{no: 1, name: 'Ngoại trang Túi Đồ hộp', cat: 'Cánh', eff: 'Công 1.5% Tăng', rate: 0.5, key: 'item-031'},
{no: 2, name: 'Ngoại trang Bóng bay trái tim', cat: 'Cánh', eff: 'HP 2.5% Tăng', rate: 0.5, key: 'item-102'},
{no: 3, name: 'Ngoại trang Truyền dịch', cat: 'Cánh', eff: 'Thủ 5% Tăng', rate: 0.5, key: 'item-109'},
{no: 4, name: 'Ngoại trang Giỏ gà chíp', cat: 'Cánh', eff: 'Công 3.0% Tăng', rate: 0.2, key: 'item-161'},
{no: 5, name: 'Ngoại trang hộ vệ', cat: 'Trang phục', eff: 'Công 0.6% Tăng', rate: 0.2, key: 'item-072'},
{no: 6, name: 'Ngoại trang bạch kim', cat: 'Trang phục', eff: 'Công 0.6% Tăng', rate: 0.2, key: 'item-129'},
{no: 7, name: 'Ngoại trang cao bồi', cat: 'Trang phục', eff: 'HP 1.6% Tăng', rate: 0.7, key: 'item-101'},
{no: 8, name: 'Ngoại trang tiệc đêm', cat: 'Trang phục', eff: 'Thủ 2% Tăng', rate: 0.7, key: 'item-059'},
{no: 9, name: 'Ngoại trang áo trench coat', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-053'},
{no: 10, name: 'Ngoại trang lễ phục mùa đông', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-054'},
{no: 11, name: 'Ngoại Trang Rùng Rợn', cat: 'Trang phục', eff: 'Công 0.3% Tăng', rate: 2.655, key: 'item-136'},
{no: 12, name: 'Ngoại Trang Bếp Trưởng', cat: 'Trang phục', eff: 'Công 0.3% Tăng', rate: 2.655, key: 'item-060'},
{no: 13, name: 'Ngoại Trang Học Sinh Thủy Thủ', cat: 'Trang phục', eff: 'Công 0.3% Tăng', rate: 2.655, key: 'item-064'},
{no: 14, name: 'Ngoại Trang Đồ Bơi', cat: 'Trang phục', eff: 'Công 0.3% Tăng', rate: 2.655, key: 'item-076'},
{no: 15, name: 'Ngoại Trang Halloween', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-093'},
{no: 16, name: 'Ngoại Trang Santa', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-099'},
{no: 17, name: 'Ngoại trang Phao hồng', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-077'},
{no: 18, name: 'Ngoại Trang Đồng Phục Đỏ', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-063'},
{no: 19, name: 'Ngoại trang gấu', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-139'},
{no: 20, name: 'Ngoại trang dạo biển', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-052'},
{no: 21, name: 'Ngoại trang thỏ hồng', cat: 'Trang phục', eff: 'Công 0.3% Tăng', rate: 2.655, key: 'item-138'},
{no: 22, name: 'Ngoại trang bánh quy gừng', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-079'},
{no: 23, name: 'Ngoại trang cà chua', cat: 'Trang phục', eff: 'Thủ 1% Tăng', rate: 2.655, key: 'item-080'},
{no: 24, name: 'Ngoại trang dứa', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-081'},
{no: 25, name: 'Ngoại trang hoa', cat: 'Trang phục', eff: 'Công 0.3% Tăng', rate: 2.655, key: 'item-006'},
{no: 26, name: 'Ngoại trang lễ phục năm mới', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-074'},
{no: 27, name: 'Ngoại trang váy xuân', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-005'},
{no: 28, name: 'Ngoại trang đồng phục hồng', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-065'},
{no: 29, name: 'Ngoại trang Dã ngoại Lilac', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-162'},
{no: 30, name: 'Trang phục Vịt Vàng', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-163'},
{no: 31, name: 'Triệu hồi Ma Bí Ngô', cat: 'Tiên', eff: '-', rate: 2.215, key: 'item-164'},
{no: 32, name: 'Phiếu triệu hồi Cá voi nhặt đồ', cat: 'Tiên', eff: '-', rate: 2.215, key: 'item-165'},
{no: 33, name: 'Vé triệu hồi người tuyết', cat: 'Tiên', eff: '-', rate: 2.215, key: 'item-166'},
{no: 34, name: 'Triệu hồi cá hề', cat: 'Tiên', eff: '-', rate: 2.215, key: 'item-167'},
{no: 35, name: 'Triệu Hồi Chim Cánh Cụt Nam Cực', cat: 'Tiên', eff: '-', rate: 2.215, key: 'item-168'},
{no: 36, name: 'Triệu Hồi Bạch Tuộc Nhặt Đồ', cat: 'Tiên', eff: '-', rate: 2.215, key: 'item-169'},
{no: 37, name: 'Ngoại trang lưỡi lực', cat: 'Vũ khí', eff: 'Chí mạng Tỉ lệ 1% Tăng', rate: 0.7, key: 'item-011'},
{no: 38, name: 'Ngoại trang búa lực', cat: 'Vũ khí', eff: 'Chí mạng Tỉ lệ 1% Tăng', rate: 0.7, key: 'item-058'},
{no: 39, name: 'Ngoại trang cung lực', cat: 'Vũ khí', eff: 'Chí mạng Tỉ lệ 1% Tăng', rate: 0.7, key: 'item-094'},
{no: 40, name: 'Ngoại trang trượng lực', cat: 'Vũ khí', eff: 'Chí mạng Tỉ lệ 1% Tăng', rate: 0.7, key: 'item-092'},
{no: 41, name: 'Ngoại trang Kiếm Đại ác ma', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-050'},
{no: 42, name: 'Ngoại trang Búa Đại ác ma', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-071'},
{no: 43, name: 'Ngoại trang Cung Đại ác ma', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-091'},
{no: 44, name: 'Ngoại trang Gậy Đại ác ma', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-118'},
{no: 45, name: 'Ngoại trang vũ khí cưa', cat: 'Vũ khí', eff: 'Chí mạng Sát thương 2% Tăng', rate: 2.4, key: 'item-008'},
{no: 46, name: 'Ngoại trang vũ khí búa', cat: 'Vũ khí', eff: 'Chí mạng Sát thương 2% Tăng', rate: 2.4, key: 'item-014'},
{no: 47, name: 'Ngoại trang vũ khí kéo', cat: 'Vũ khí', eff: 'Chí mạng Sát thương 2% Tăng', rate: 2.4, key: 'item-012'},
{no: 48, name: 'Ngoại trang vũ khí cờ lê', cat: 'Vũ khí', eff: 'Chí mạng Sát thương 2% Tăng', rate: 2.4, key: 'item-013'},
{no: 49, name: 'Ngoại trang vũ khí Violin', cat: 'Vũ khí', eff: 'HP 2% Tăng', rate: 2.4, key: 'item-009'},
{no: 50, name: 'Ngoại trang vũ khí guitar điện', cat: 'Vũ khí', eff: 'HP 2% Tăng', rate: 2.4, key: 'item-056'},
{no: 51, name: 'Ngoại trang vũ khí đàn Harp', cat: 'Vũ khí', eff: 'HP 2% Tăng', rate: 2.4, key: 'item-096'},
{no: 52, name: 'Ngoại trang vũ khí Micro', cat: 'Vũ khí', eff: 'HP 2% Tăng', rate: 2.4, key: 'item-082'},
];

export const boxBItems = [
{no: 1, name: 'Ngoại Trang Cánh Bướm', cat: 'Cánh', eff: 'Quái nhân 5% Sát thương Tăng', rate: 0.2, key: 'item-004'},
{no: 2, name: 'Ngoại Trang Cánh Quạ', cat: 'Cánh', eff: 'Chí mạng Sát thương 5% Tăng', rate: 0.2, key: 'item-018'},
{no: 3, name: 'Ngoại Trang Cánh Tiên Nữ', cat: 'Cánh', eff: 'Chí mạng Tỉ lệ 2% Tăng', rate: 0.2, key: 'item-019'},
{no: 4, name: 'Cánh sáng chói', cat: 'Cánh', eff: 'Công 3% Tăng', rate: 0.2, key: 'item-170'},
{no: 5, name: 'Ngoại trang vua phía Bắc', cat: 'Trang phục', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-017'},
{no: 6, name: 'Ngoại trang Hầu gái Mèo', cat: 'Trang phục', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-085'},
{no: 7, name: 'Ngoại trang Cương thi', cat: 'Trang phục', eff: 'HP 1.6% Tăng', rate: 0.7, key: 'item-112'},
{no: 8, name: 'Ngoại Trang Triều Đại thời Joseon', cat: 'Trang phục', eff: 'Kinh nghiệm 5% Tăng', rate: 2.655, key: 'item-075'},
{no: 9, name: 'Ngoại trang Người sành điệu mùa thu', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-083'},
{no: 10, name: 'Ngoại trang Pháp sư Bí ngô', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-110'},
{no: 11, name: 'Ngoại trang Tiệc cuối năm', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-067'},
{no: 12, name: 'Ngoại trang Tiên Noel', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-068'},
{no: 13, name: 'Ngoại trang Kẹo ngọt', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-087'},
{no: 14, name: 'Ngoại trang Thủy thủ mùa hè', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-171'},
{no: 15, name: 'Ngoại trang Thỏ vũ trụ', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-103'},
{no: 16, name: 'Ngoại trang phù thủy đen', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-111'},
{no: 17, name: 'Ngoại trang trang trọng Holiday', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-069'},
{no: 18, name: 'Ngoại trang Ếch xanh', cat: 'Trang phục', eff: 'Công 0.3% Tăng', rate: 2.655, key: 'item-084'},
{no: 19, name: 'Ngoại trang Hoàng tử & Công chúa', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-086'},
{no: 20, name: 'Ngoại trang Đồ ngủ', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-088'},
{no: 21, name: 'Ngoại Trang Tiệc Dã Ngoại', cat: 'Trang phục', eff: 'Thủ 1% Tăng', rate: 2.655, key: 'item-078'},
{no: 22, name: 'Ngoại Trang Chiến Binh', cat: 'Trang phục', eff: 'Thủ 1% Tăng', rate: 2.655, key: 'item-172'},
{no: 23, name: 'Ngoại Trang Bánh Gatô', cat: 'Trang phục', eff: 'Thủ 1% Tăng', rate: 2.655, key: 'item-061'},
{no: 24, name: 'Ngoại trang Dã ngoại Xuân', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-173'},
{no: 25, name: 'Ngoại trang Kỳ nghỉ hè', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-174'},
{no: 26, name: 'Ngoại trang Hạt sồi', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-175'},
{no: 27, name: 'Ngoại trang Mèo Noel', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-176'},
{no: 28, name: 'Ngoại trang thường màu xanh', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-177'},
{no: 29, name: 'Ngoại trang Dạ hội lộng lẫy', cat: 'Trang phục', eff: 'HP 0.8% Tăng', rate: 2.655, key: 'item-178'},
{no: 30, name: 'Vé triệu hồi Cá voi sát thủ Looting', cat: 'Tiên', eff: '-', rate: 2.315, key: 'item-179'},
{no: 31, name: 'Vé triệu hồi Chim cánh cụt Looting', cat: 'Tiên', eff: '-', rate: 2.315, key: 'item-180'},
{no: 32, name: 'Vé triệu hồi Chim hồng hạc', cat: 'Tiên', eff: '-', rate: 2.315, key: 'item-181'},
{no: 33, name: 'Vé triệu hồi Cá Jelly', cat: 'Tiên', eff: '-', rate: 2.315, key: 'item-182'},
{no: 34, name: 'Vé triệu hồi Ong mật Jelly', cat: 'Tiên', eff: '-', rate: 2.315, key: 'item-183'},
{no: 35, name: 'Vé triệu hồi Chim cánh cụt nhặt đồ', cat: 'Tiên', eff: '-', rate: 2.315, key: 'item-184'},
{no: 36, name: 'Ngoại Trang Kiếm Tổng Lãnh Thiên Thần', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-010'},
{no: 37, name: 'Ngoại Trang Búa Tổng Lãnh Thiên Thần', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-057'},
{no: 38, name: 'Ngoại Trang Cung Tổng Lãnh Thiên Thần', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-097'},
{no: 39, name: 'Ngoại Trang Trượng Tổng Lãnh Thiên Thần', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-106'},
{no: 40, name: 'Ngoại trang Kiếm Rồng Xanh', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-185'},
{no: 41, name: 'Ngoại trang Búa Rồng Xanh', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-186'},
{no: 42, name: 'Ngoại trang Cung Rồng Xanh', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-187'},
{no: 43, name: 'Ngoại trang Lord Rồng Xanh', cat: 'Vũ khí', eff: 'Công 0.6% Tăng', rate: 0.7, key: 'item-188'},
{no: 44, name: 'Ngoại trang Vũ khí Xúc xích', cat: 'Vũ khí', eff: 'HP 2% Tăng', rate: 2.4, key: 'item-033'},
{no: 45, name: 'Ngoại trang Vũ khí Sườn cừu', cat: 'Vũ khí', eff: 'HP 2% Tăng', rate: 2.4, key: 'item-035'},
{no: 46, name: 'Ngoại trang Vũ khí Pretzel', cat: 'Vũ khí', eff: 'HP 2% Tăng', rate: 2.4, key: 'item-032'},
{no: 47, name: 'Ngoại trang Vũ khí Bông lan cuộn', cat: 'Vũ khí', eff: 'HP 2% Tăng', rate: 2.4, key: 'item-034'},
{no: 48, name: 'Ngoại Trang Vũ Khí Cà Rốt Tươi', cat: 'Vũ khí', eff: 'Thủ 3% Tăng', rate: 2.4, key: 'item-007'},
{no: 49, name: 'Ngoại Trang Vũ Khí Băng Nhũ', cat: 'Vũ khí', eff: 'Thủ 3% Tăng', rate: 2.4, key: 'item-055'},
{no: 50, name: 'Ngoại Trang Vũ Khí Hải Mã', cat: 'Vũ khí', eff: 'Thủ 3% Tăng', rate: 2.4, key: 'item-095'},
{no: 51, name: 'Ngoại Trang Vũ Khí Kẹo Mút', cat: 'Vũ khí', eff: 'Thủ 3% Tăng', rate: 2.4, key: 'item-105'},
];

export const chonbiItems = [
{name: 'Ngoại trang Cánh rồng hỗn độn', cat: 'Ngoại trang', rate: 0.4, key: 'item-047'},
{name: 'Ngoại trang Cánh sương giá', cat: 'Ngoại trang', rate: 0.4, key: 'item-048'},
{name: 'Ngoại trang cánh giấc mơ', cat: 'Ngoại trang', rate: 0.4, key: 'item-049'},
{name: 'Ngoại trang quý tộc mùa đông', cat: 'Ngoại trang', rate: 1.0, key: 'item-124'},
{name: 'Ngoại trang ong mật', cat: 'Ngoại trang', rate: 1.0, key: 'item-090'},
{name: 'Trang phục ngủ màu cam', cat: 'Ngoại trang', rate: 2.0, key: 'item-089'},
{name: 'Ngoại trang Đồng phục xưa', cat: 'Ngoại trang', rate: 2.0, key: 'item-070'},
{name: 'Ngoại trang Kiếm đáng yêu', cat: 'Ngoại trang', rate: 1.0, key: 'item-040'},
{name: 'Ngoại trang Búa đáng yêu', cat: 'Ngoại trang', rate: 1.0, key: 'item-042'},
{name: 'Ngoại trang Cung đáng yêu', cat: 'Ngoại trang', rate: 1.0, key: 'item-039'},
{name: 'Ngoại trang Đũa phép đáng yêu', cat: 'Ngoại trang', rate: 1.0, key: 'item-041'},
{name: 'Ngoại trang Vũ khí nĩa', cat: 'Ngoại trang', rate: 2.0, key: 'item-044'},
{name: 'Ngoại trang Vũ khí bánh cá', cat: 'Ngoại trang', rate: 2.0, key: 'item-046'},
{name: 'Ngoại trang Vũ khí tôm', cat: 'Ngoại trang', rate: 2.0, key: 'item-043'},
{name: 'Ngoại trang Vũ khí Marshmallow', cat: 'Ngoại trang', rate: 2.0, key: 'item-045'},
{name: 'Thỉnh Cầu Thợ Săn Thần x3', cat: 'Thỉnh cầu Thợ săn', rate: 8.0},
{name: 'Thỉnh Cầu Thợ Săn Superior x2', cat: 'Thỉnh cầu Thợ săn', rate: 3.5},
{name: 'Sách Buff EXP x10', cat: 'Sách', rate: 5.0},
{name: 'Sách Rớt Vật Phẩm x10', cat: 'Sách', rate: 5.0},
{name: 'Sách Cường hóa Trang bị cấp độ 20 x1', cat: 'Khác', rate: 3.0},
{name: 'Sách Chất Lượng Tối Thượng x1', cat: 'Khác', rate: 0.5},
{name: 'Sách Nhận Lại Trang Bị x2', cat: 'Khác', rate: 3.5},
{name: 'Tiên Dược Tính Cách Ngẫu Nhiên x1', cat: 'Khác', rate: 3.0},
{name: 'Đá thức tỉnh x1', cat: 'Khác', rate: 0.3},
{name: 'Tiên Dược Reset thay đổi Lớp x1', cat: 'Khác', rate: 3.0},
{name: 'Gói Bí Kíp Đặc Biệt x1', cat: 'Khác', rate: 5.0},
{name: 'Bộ Sách kỹ thuật đặc biệt cổ đại x10', cat: 'Khác', rate: 5.0},
{name: 'Mảnh hoa văn đặc biệt x3', cat: 'Khác', rate: 3.0},
{name: 'Vé triệu hồi Răng hàm Tứ thiên vương x2', cat: 'Khác', rate: 5.0},
{name: 'Tượng vàng đặc biệt x20', cat: 'Khác', rate: 5.0},
{name: 'Rương Hắc Linh Đặc Biệt x1', cat: 'Khác', rate: 3.0},
{name: 'Xu tỏa sáng x5', cat: 'Khác', rate: 3.0},
{name: 'Xu tỏa sáng x10', cat: 'Khác', rate: 1.5},
{name: 'Quặng cường hóa x100', cat: 'Khác', rate: 3.5},
{name: 'Sách loại bỏ thuộc tính x5', cat: 'Khác', rate: 5.0},
{name: 'Sách loại bỏ thuộc tính x10', cat: 'Khác', rate: 2.5},
{name: 'Vé reset lượt loại bỏ thuộc tính x1', cat: 'Khác', rate: 2.0},
{name: 'Chìa khóa Hành lang Thành ma vương x1', cat: 'Khác', rate: 2.5},
];

export const boxes = [
  {id: 'Lấp LánhA', label: 'Hộp ngoại trang lấp lánh A', items: boxAItems},
  {id: 'Lấp LánhB', label: 'Hộp ngoại trang lấp lánh B', items: boxBItems},
  {id: 'Rương Bí Mật', label: 'Rương bí mật Thị trưởng (Ngoại trang)', items: chonbiItems.filter(i => i.key)},
];
